cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^add_item/(?P<pk>[0-9]+)$', views.add_cart_item, name='add_item'),
    url(r'^cart_content/$', views.CartView.as_view(), name='cart_content'),
    url(r'^save_cart_item/(?P<pk>[0-9]+)$', views.save_cart_item, name='save_cart_item'),
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^remove_item/(?P<pk>[0-9]+)$', views.remove_cart_item, name='remove_item'),
    url(r'^remove_item_from_vente/(?P<pk>[0-9]+)$', views.remove_article_from_vente_and_update_article_quantity,
        name='remove_article_from_vente'),
    url(r'^edit_price/(?P<pk>[0-9]+)$', views.edit_price, name='edit_price'),
    url(r'^edit_quantity/(?P<pk>[0-9]+)$', views.edit_quantity, name='edit_quantity'),
    url(r'^vente/(?P<pk>[0-9]+)$', views.VenteDetail.as_view(), name='vente'),
    url(r'^vente_update/(?P<pk>[0-9]+)$', views.VenteUpdateView.as_view(), name='vente_update'),
    #url(r'^vente_delete/(?P<pk>[0-9]+)$', views.VenteDeleteView.as_view(), name='vente_delete'),
    url(r'^vente_delete/(?P<pk>[0-9]+)$', views.vente_delete, name='vente_delete'),
    url(r'^ventes/$', views.VenteListView.as_view(), name='ventes'),
    url(r'^clients/$', views.ClientListView.as_view(), name='clients'),
    url(r'^client/(?P<pk>[0-9]+)$', views.ClientDetailView.as_view(), name='client'),
    url(r'^client_update/(?P<pk>[0-9]+)$', views.ClientUpdateView.as_view(), name='client_update'),
    url(r'^client_delete/(?P<pk>[0-9]+)$', views.ClientDeleteView.as_view(), name='client_delete'),
    url(r'^client_create/$', views.ClientCreateView.as_view(), name='client_create'),
    url(r'^paiements/$', views.PaiementListView.as_view(), name='paiements'),
    url(r'^paiement_add/(?P<vente_pk>[0-9]+)$', views.add_paiement, name='paiement_add'),
    url(r'^paiement/(?P<pk>[0-9]+)$', views.PaiementDetailView.as_view(), name='paiement'),
    url(r'^paiement_update/(?P<pk>[0-9]+)$', views.PaiementUpdateView.as_view(), name='paiement_update'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.views import defaults as default_views
from dproject.views import IndexView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace="cart")),
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    url(r'^costs/', include('costs.urls', namespace="costs")),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^', include('favicon.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns


if 'cms' in settings.INSTALLED_APPS:
    from django.contrib.sitemaps.views import sitemap
    from cms.sitemaps import CMSSitemap
    urlpatterns += [
        url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
        url(r'^', include('cms.urls')),
    ]
else:
    urlpatterns += [
        url(r'^$', IndexView.as_view(), name='home'),
    ]

if 'imprint' in settings.INSTALLED_APPS:
    from imprint.views import AboutView
    urlpatterns += [
        url(r'^about/$', AboutView.as_view(), name='about'),
    ]

costs/urls.py
from django.conf.urls import url
from . import views


app_name = 'costs'

urlpatterns = [
    url(r'^category_create/$', views.CategoryCreateView.as_view(), name='category_create'),
    url(r'^category_details/(?P<pk>[0-9]+)$', views.CategoryDetailView.as_view(), name='category_details'),
    url(r'^category_update/(?P<pk>[0-9]+)$', views.CategoryUpdateView.as_view(), name='category_update'),
    url(r'^category_delete/(?P<pk>[0-9]+)$', views.CategoryDeleteView.as_view(), name='category_delete'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='categories'),
    url(r'^enterprise_create/$', views.EnterpriseCreateView.as_view(), name='enterprise_create'),
    url(r'^enterprise_details/(?P<pk>[0-9]+)$', views.EnterpriseDetailView.as_view(), name='enterprise_details'),
    url(r'^enterprise_update/(?P<pk>[0-9]+)$', views.EnterpriseUpdateView.as_view(), name='enterprise_update'),
    url(r'^enterprise_delete/(?P<pk>[0-9]+)$', views.EnterpriseDeleteView.as_view(), name='enterprise_delete'),
    url(r'^enterprises/$', views.EnterpriseListView.as_view(), name='enterprises'),
    url(r'^costs_create/$', views.CostsCreateView.as_view(), name='costs_create'),
    url(r'^costs/$', views.CostsListView.as_view(), name='costs'),
    url(r'^costs_branch/(?P<pk>[0-9]+)$', views.CostsPerBranch.as_view(), name='costs_branch'),
    url(r'^costs_details/(?P<pk>[0-9]+)$', views.CostsDetailView.as_view(), name='costs_details'),
    url(r'^costs_update/(?P<pk>[0-9]+)$', views.CostsUpdateView.as_view(), name='costs_update'),
    url(r'^costs_delete/(?P<pk>[0-9]+)$', views.CostsDeleteView.as_view(), name='costs_delete'),
    ]

dashboard/urls.py
from django.conf.urls import url
from . import views


app_name = 'dashboard'

urlpatterns = [
    #url(r'^main/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})*$', views.MainBalanceView.as_view(), name='main'),
    url(r'^main/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})*$', views.MainBalanceView.as_view(), name='main'),
    url(r'^main/(?P<start_date>[0-9]{4}-[0-9]{2}-[0-9]{2})(?P<end_date>[0-9]{4}-[0-9]{2}-[0-9]{2})$', views.MainBalanceView.as_view(), name='main'),
    url(r'^branch/(?P<pk>[0-9]+)/', views.branch_dashboard, name='branch'),
    ]

inventory/urls.py
from django.conf.urls import url
from .views import ArticleDetailView, articles, ArticleUpdateView, articleDeleteView, ArticlesByPicturesView
from .views import ArrivalListView, ArrivalUpdateView, ArrivalCreateView, ArrivalDetailView, ArrivalDeleteView
from .views import handle_pictures, upload_pictures_zip, CategoryCreateView, CategoryUpdateView, CategoryListView
from .views import CategoryDetailView, CategoryDeleteView
from .views import add_one_loss, BranchCreateView, BranchDetailView, BranchDeleteView
from .views import BranchListView, BranchEditView
from .views import LossDeleteView, LossesListView, LossUpdateView, LossDetailView


app_name = 'inventory'


urlpatterns = [
    url(r'^arrival_create/$', ArrivalCreateView.as_view(), name='arrival_create'),
    url(r'^arrival_detail/(?P<pk>[0-9]+)$', ArrivalDetailView.as_view(), name='arrival_detail'),
    url(r'^arrival_update/(?P<pk>[0-9]+)$', ArrivalUpdateView.as_view(), name='arrival_update'),
    url(r'^arrival_delete/(?P<pk>[0-9]+)$', ArrivalDeleteView.as_view(), name='arrival_delete'),
    url(r'^arrivals/$', ArrivalListView.as_view(), name='arrivals'),
    url(r'^categories/$', CategoryListView.as_view(), name='categories'),
    url(r'^category_update/(?P<pk>[0-9]+)$', CategoryUpdateView.as_view(), name='category_update'),
    url(r'^category_create/$', CategoryCreateView.as_view(), name='category_create'),
    url(r'^category_detail/(?P<pk>[0-9]+)$', CategoryDetailView.as_view(), name='category_detail'),
    url(r'^category_delete/(?P<pk>[0-9]+)$', CategoryDeleteView.as_view(), name='category_delete'),
    url('articles/', articles, name='articles'),
    url(r'articles_by_pictures/$', ArticlesByPicturesView.as_view(), name='articles_by_pictures'),

    url(r'^loss_delete/(?P<pk>[0-9]+)$', LossDeleteView.as_view(), name='loss_delete'),
    url(r'^loss_update/(?P<pk>[0-9]+)$', LossUpdateView.as_view(), name='loss_update'),
    url(r'^loss_detail/(?P<pk>[0-9]+)$', LossDetailView.as_view(), name='loss_detail'),
    url(r'^losses/$', LossesListView.as_view(), name='losses'),

    url('branches/', BranchListView.as_view(), name='branches'),
    url('branch_create/$', BranchCreateView.as_view(), name='branch_create'),
    url('branch_detail/(?P<pk>[0-9]+)$', BranchDetailView.as_view(), name='branch_detail'),
    url('branch_delete/(?P<pk>[0-9]+)$', BranchDeleteView.as_view(), name='branch_delete'),
    url('branch_update/(?P<pk>[0-9]+)$', BranchEditView.as_view(), name='branch_update'),

    url(r'article_update/(?P<pk>[0-9]+)$', ArticleUpdateView.as_view(), name='article_update'),
    url(r'article_losses/(?P<pk>[0-9]+)$', add_one_loss, name='article_losses'),
    #url(r'add_one_loss/(?P<pk>[0-9]+)$', AddOneLossView.as_view(), name='add_one_loss'),
    url(r'^article_detail/(?P<pk>[0-9]+)$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article_delete/(?P<pk>[0-9]+)$', articleDeleteView, name='article_delete'),
    #url(r'^upload_pic/(?P<pk>[0-9]+)$', upload_pic, name='upload_pic'),
    url(r'^handle_pics/$', handle_pictures, name='handle_pics'),
    url(r'^upload_zipics/$', upload_pictures_zip, name='upload_zipics'),
]

dproject/views.py
from django.views.generic import TemplateView
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.sites.shortcuts import get_current_site
from inventory.models import Employee, Article, Branch


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['site'] = get_current_site(self.request)
        if '.prestigemikafric.com' in settings.ALLOWED_HOSTS:
            pass
        else:
            context['DEV'] = 'DEV'


        articles_en_soldes = Article.objects.filter(solde='S')
        paginator = Paginator(articles_en_soldes, 15)
        page = self.request.GET.get('page')
        start_index = 1
        try:
            articles = paginator.page(page)
            start_index = articles.start_index()
        except PageNotAnInteger:
            articles = paginator.page(1)
        except EmptyPage:
            articles = paginator.page(paginator.num_pages)  # last page
            start_index = articles.start_index()
        context['soldes'] = articles
        context['count'] =  articles_en_soldes.count()
        context['start_index'] = start_index
        context['branches'] = Branch.objects.all()

        user = self.request.user
        if user.is_authenticated:
            try:
                context['employee'] = Employee.objects.get(user=user)
            except:
                context['employee'] = None
        return context

dproject/templates/403_csrf.html
{% load i18n %}

{% block title %}{% trans 'CSRF verification failed. Request aborted.' %}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>{% trans 'CSRF verification failed. Request aborted.' %}</h1>
    </div>
  </div>
</div>
{% endblock content %}

dproject/templates/about.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

{% block title %}{{ site.name }}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>{% trans 'Imprint' %}</h1>
      <p>
        {% if site.ownership.company_name %}{{ site.ownership.company_name }}<br />{% endif %}
        {{ site.ownership.first_name }} {{ site.ownership.last_name }}<br />
        {{ site.ownership.postal_code }} {{ site.ownership.place }}<br />
        {{ site.ownership.country_name }}<br />
      </p>
    </div>
  </div>
</div>
{% endblock %}

dproject/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n %}
{% load branches_list %}


{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

<html lang="{{ LANGUAGE_CODE }}" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

    <!-- Third-party CSS libraries go here -->
    <link href="{% static 'bootstrap3/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap3/css/bootstrap-dialog.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    <!--ajouté par moi pour datepicker jquery-->
    <link rel="stylesheet" href="/static/jqueryui/jquery-ui.min.css">



    <!-- Project specific CSS -->
    {% block css %}
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand logo" href="/">Cosas de casa</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
              <li><a href="{% url 'about' %}">{% trans 'About' %}</a></li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ LANGUAGE_CODE }}</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown02">{% for lang in LANGUAGES %}
                  <form id="formsetLang{{ lang.0 }}" action="{% url 'set_language' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="language" value="{{ lang.0 }}" />
                    <input type="hidden" name="next" value="{{ request.get_full_path }}" />
                  </form>
                  <li><a class="language_changer" id="{{ lang.0 }}" href="#">{{ lang.1 }}</a></li>
                {% endfor %}
                </ul>
              </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {% trans "First Steps" %}
                       <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header"><span class="glyphicon glyphicon-pencil"></span>  Preparation</li>
                        <li><a href="{% url "inventory:branch_create" %}">{% trans 'Create Branch' %}</a> </li>
                        <li><a href="{% url "inventory:category_create" %}" title="{% trans 'Create category' %}">{% trans 'Create one Category' %}</a></li>
                        <li><a href="{% url "inventory:arrival_create" %}" title="{% trans 'Create  Arrival' %}"> {% trans 'Create one Arrival' %}</a></li>
                        <li><a href="{% url "inventory:upload_zipics" %}" title="{% trans 'Upload pictures ZIP' %}">{% trans 'Upload ZIP pictures' %}</a></li>
                        <li><a href="{% url "inventory:handle_pics" %}" title="{% trans 'Generate articles from pictures' %}">{% trans 'Generate Articles' %}</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">{% trans 'Your Basic Data'%}</li>
                        <li><a href="{% url "inventory:branches" %}"><span class="glyphicon glyphicon-list-alt"></span>  {% trans 'Branches' %}</a> </li>
                        <li><a href="{% url "inventory:arrivals" %}" title="{% trans 'Arrivals List' %}"><span class="glyphicon glyphicon-list-alt"></span>  {% trans 'Arrivals' %}</a></li>
                        <li><a href="{% url "inventory:categories" %}" title="{% trans 'List the categories' %}"><span class="glyphicon glyphicon-list-alt"></span>  {% trans 'Categories' %}</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {% trans "Caisse" %}
                       <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "inventory:articles" %}" title="{% trans 'Liste des articles' %}"><span class="glyphicon glyphicon-list-alt"></span>  {% trans 'Liste des articles' %}</a></li>
                        <li><a href="{% url "inventory:articles_by_pictures" %}"><span class="glyphicon glyphicon-camera"></span>  {% trans "Articles by pics" %}<a/></li>
                        <li class="divider"></li>
                        <li><a href="{% url "cart:cart_content" %}"><span class="glyphicon glyphicon-shopping-cart"></span>  {%trans 'Contenu du panier' %}</a></li>
                        <li><a href="{% url "cart:ventes"  %}"><span class="glyphicon glyphicon-money"></span>{% trans 'Ventes' %}</a></li>
                        <li><a href="{% url "cart:paiements"  %}">{% trans 'Payments' %}</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url "cart:clients" %}"><span class="glyphicon glyphicon-user"></span>  {% trans 'Clients' %}</a></li>
                        <li><a href="{% url "cart:client_create" %}"><span class="glyphicon glyphicon-pencil"></span>  {% trans 'Ajouter un client' %}</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                  <a class="dropdown-toggle" href="#" data-toggle="dropdown">{% trans "Costs" %}
                  <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url "costs:costs" %}">{% trans "Costs" %}</a> </li>
                    <li><a title="{% trans 'Adding a lost is possible in article details view' %}" href="{% url "inventory:losses" %}">{% trans "Losses" %}</a> </li>
                    <li><a href="{% url "costs:costs_create" %}">{% trans "Add one Cost" %}</a> </li>
                    <li class="divider"></li>
                    <li><a href="{% url "costs:categories" %}"><span class="glyphicon glyphicon-tags"></span>  {% trans "Categories" %}</a> </li>
                    <li><a href="{% url "costs:category_create" %}"><span class="glyphicon glyphicon-pencil"></span>  {% trans "Create a category" %}</a> </li>
                    <li class="divider"></li>
                    <li><a href="{% url "costs:enterprises" %}"><span class="glyphicon glyphicon-list-alt"></span>  {% trans "Enterprises" %}</a> </li>
                    <li><a href="{% url "costs:enterprise_create" %}"
                      title="{% trans 'an enterprise or provider which occurs regularly in your costs' %}"><span class="glyphicon glyphicon-pencil"></span>  {% trans "Create an enterprise" %}</a> </li>
                  </ul>
                </li>

                <li class="dropdown"><a href="#" data-toggle="dropdown"><span class="glyphicon glyphicon-stats"></span> Dashboard<span class="caret"</span></a>
                    <ul class="dropdown-menu">
                      <li><a title="All Branches" href="{% url 'dashboard:main' %}">Main</a> </li>
                      {% show_branches %}
                    </ul>
                </li>
            {% endif %}

            {%  if user.is_authenticated %}

            <li><a href="{% url 'logout' %}">{% trans 'Log out' %}</a></li>
            {% else %}
            <li>
              <a class="active" href="{% url 'login' %}">{% trans 'Log in' %} <span class="fa fa-sign-in"></span></a>
            </li>
            {% endif %}
          </ul>
        </div>
        </div>
	  </nav>

    <div class="content">

      {% if messages %}
        <div class="container">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ forloop.counter }}. {{ message }}</div>
          {% endfor %}
        </div>
      {% endif %}

      {% block content %}
      {% endblock content %}
    </div>

    <div class="container">
    {% block footernav %}

    {% endblock %}
    </div>

    {% block footer %}

    <!--<footer class="footer">-->
      <!--<nav class="navbar navbar-default navbar-fixed-bottom">-->
        <!--<div class="container-fluid">-->
          <!--<div class="container">-->
            <!--<div class="navbar-header">-->
              <!--<a class="navbar-brand" href="http://metacoherence.ch/" target="_blank">{% trans 'créé par' %} <b>Metacoherence</b>-->
              <!--</a>-->
            <!--</div>-->
            <!--<ul class="nav navbar-nav navbar-right">-->
              <!--<li><a>Version 0.0.2</a></li>-->
            <!--</ul>-->
          <!--</div>-->
        <!--</div>-->
      <!--</nav>-->
    <!--</footer>-->
    {% endblock %}

    <!-- Third-party javascript libraries go here -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'jquery/js.cookie.js' %}"></script>
    <!--mon ajout-->
    <script src="/static/jqueryui/jquery-ui.min.js"></script>
    <script src="{% static 'bootstrap3/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap3/js/bootstrap-dialog.min.js' %}"></script>
    <script src="{% static 'js/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>


    <!--ajouté par moi-->
    <script src="{% static 'js/project.js' %}"></script>
    <script src="/static/jquery/jqueryhello.js"></script>
    <script src="/static/jqueryui/external/jquery/jquery-3.2.1.min.js"></script>
    <script src="/static/jqueryui/jquery-ui.min.js"></script>
    <script src="/static/jqueryui/i18n/datepicker-es.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>

    <!-- Project specific javascript -->
    {% block javascript %}
    {% endblock javascript %}

  </body>
</html>

dproject/templates/bs3-menu.html
{% load menu_tags %}
{% load i18n menu_tags cache mptt_tags %}


{% for child in children %}
<li class="{% if child.selected or child.ancestor %}active{% endif %}{% if child.children %} dropdown{% endif %} menu-li">
	{% if child.children %}
	<a href="{{ child.get_absolute_url }}">{{ child.get_menu_title }} </a>
	<span class="caret" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button"></span>
	<ul class="dropdown-menu">
		{% for grandchild in child.children %}
			<li{% if grandchild.selected %} class="active"{% endif %}>
				<a href="{{ grandchild.attr.redirect_url|default:grandchild.get_absolute_url }}">{{ grandchild.get_menu_title }}</a>
			</li>
		{% endfor %}
	</ul>
	{% else %}
	<a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
	{% endif %}
</li>
{% endfor %}

dproject/templates/inventex.html
{% extends "base.html" %}
{% load static %}
{% block header %}Inventaires{% endblock %}
{% block site_wrapper %}

<div class="container-fluid">

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar/brand" href="/"><h3>Prestigemikafriq</h3></a>
            </div>
            <ul class="nav navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Arrivages<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Créer un arrivage</a></li>
                        <li><a href="#">Arrivages</a></li>
                        <li><a href="#">Liste des frais</a></li>
                    </ul>
                </li>
                {% endif %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Articles<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "inventory:articles" %}" title="Liste des articles">Liste des articles</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url "inventory:article_create" %}" title="Saisir un article">Saisir un article</a></li>
                        <li><a href="#" title="Générer étiquettes avec pdflatex" target="_blank">Générer étiquettes</a></li>
                        {% endif %}
                    </ul>
                </li>
                        {% if request.user.is_authenticated %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Caisse<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "cart:cart_content" %}">Contenu du panier</a></li>
                        <li><a href="{% url "cart:ventes"  %}">Ventes</a></li>
                        <li><a href="{% url "cart:clients" %}">Clients</a></li>
                        <li><a href="{% url "cart:client_create" %}">Ajouter un client</a></li>
                    </ul>
                </li>
                        {% endif %}
                <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url "accounts:logout" %}"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
                    <p class="navbar-text">En ligne: {{request.user.username}}</p>
                {% else %}
                    <li><a href="{% url "accounts:login" %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
                {% endif %}
            </ul>
        </div>
    </nav>

        {% block content %}

        {% endblock %}
    <footer>
        <nav id="footernav">
            {% block footernav %}{% endblock %}
        </nav>
    </footer>
</div>
{% endblock %}