cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^add_item/(?P<pk>[0-9]+)$', views.add_cart_item, name='add_item'),
    url(r'^cart_content/$', views.CartView.as_view(), name='cart_content'),
    url(r'^save_cart_item/(?P<pk>[0-9]+)$', views.save_cart_item, name='save_cart_item'),
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^remove_item/(?P<pk>[0-9]+)$', views.remove_cart_item, name='remove_item'),
    url(r'^remove_item_from_vente/(?P<pk>[0-9]+)$', views.remove_article_from_vente_and_update_article_quantity,
        name='remove_article_from_vente'),
    url(r'^edit_price/(?P<pk>[0-9]+)$', views.edit_price, name='edit_price'),
    url(r'^edit_quantity/(?P<pk>[0-9]+)$', views.edit_quantity, name='edit_quantity'),
    url(r'^vente/(?P<pk>[0-9]+)$', views.VenteDetail.as_view(), name='vente'),
    url(r'^vente_update/(?P<pk>[0-9]+)$', views.VenteUpdateView.as_view(), name='vente_update'),
    #url(r'^vente_delete/(?P<pk>[0-9]+)$', views.VenteDeleteView.as_view(), name='vente_delete'),
    url(r'^vente_delete/(?P<pk>[0-9]+)$', views.vente_delete, name='vente_delete'),
    url(r'^ventes/$', views.VenteListView.as_view(), name='ventes'),
    url(r'^clients/$', views.ClientListView.as_view(), name='clients'),
    url(r'^client/(?P<pk>[0-9]+)$', views.ClientDetailView.as_view(), name='client'),
    url(r'^client_update/(?P<pk>[0-9]+)$', views.ClientUpdateView.as_view(), name='client_update'),
    url(r'^client_delete/(?P<pk>[0-9]+)$', views.ClientDeleteView.as_view(), name='client_delete'),
    url(r'^client_create/$', views.ClientCreateView.as_view(), name='client_create'),
    url(r'^paiements/$', views.PaiementListView.as_view(), name='paiements'),
    url(r'^paiement_add/(?P<vente_pk>[0-9]+)$', views.add_paiement, name='paiement_add'),
    url(r'^paiement/(?P<pk>[0-9]+)$', views.PaiementDetailView.as_view(), name='paiement'),
    url(r'^paiement_update/(?P<pk>[0-9]+)$', views.PaiementUpdateView.as_view(), name='paiement_update'),
    ]

inventory/urls.py
from django.conf.urls import url
from .views import ArticleDetailView, articles, ArticleUpdateView, articleDeleteView, ArticlesByPicturesView
from .views import ArrivalListView, ArrivalUpdateView, ArrivalCreateView, ArrivalDetailView, ArrivalDeleteView
from .views import handle_pictures, upload_pictures_zip, CategoryCreateView, CategoryUpdateView, CategoryListView
from .views import CategoryDetailView, CategoryDeleteView
from .views import add_one_loss, BranchCreateView, BranchDetailView, BranchDeleteView
from .views import BranchListView, BranchEditView
from .views import LossDeleteView, LossesListView, LossUpdateView, LossDetailView


app_name = 'inventory'


urlpatterns = [
    url(r'^arrival_create/$', ArrivalCreateView.as_view(), name='arrival_create'),
    url(r'^arrival_detail/(?P<pk>[0-9]+)$', ArrivalDetailView.as_view(), name='arrival_detail'),
    url(r'^arrival_update/(?P<pk>[0-9]+)$', ArrivalUpdateView.as_view(), name='arrival_update'),
    url(r'^arrival_delete/(?P<pk>[0-9]+)$', ArrivalDeleteView.as_view(), name='arrival_delete'),
    url(r'^arrivals/$', ArrivalListView.as_view(), name='arrivals'),
    url(r'^categories/$', CategoryListView.as_view(), name='categories'),
    url(r'^category_update/(?P<pk>[0-9]+)$', CategoryUpdateView.as_view(), name='category_update'),
    url(r'^category_create/$', CategoryCreateView.as_view(), name='category_create'),
    url(r'^category_detail/(?P<pk>[0-9]+)$', CategoryDetailView.as_view(), name='category_detail'),
    url(r'^category_delete/(?P<pk>[0-9]+)$', CategoryDeleteView.as_view(), name='category_delete'),
    url('articles/', articles, name='articles'),
    url(r'articles_by_pictures/$', ArticlesByPicturesView.as_view(), name='articles_by_pictures'),

    url(r'^loss_delete/(?P<pk>[0-9]+)$', LossDeleteView.as_view(), name='loss_delete'),
    url(r'^loss_update/(?P<pk>[0-9]+)$', LossUpdateView.as_view(), name='loss_update'),
    url(r'^loss_detail/(?P<pk>[0-9]+)$', LossDetailView.as_view(), name='loss_detail'),
    url(r'^losses/$', LossesListView.as_view(), name='losses'),

    url('branches/', BranchListView.as_view(), name='branches'),
    url('branch_create/$', BranchCreateView.as_view(), name='branch_create'),
    url('branch_detail/(?P<pk>[0-9]+)$', BranchDetailView.as_view(), name='branch_detail'),
    url('branch_delete/(?P<pk>[0-9]+)$', BranchDeleteView.as_view(), name='branch_delete'),
    url('branch_update/(?P<pk>[0-9]+)$', BranchEditView.as_view(), name='branch_update'),

    url(r'article_update/(?P<pk>[0-9]+)$', ArticleUpdateView.as_view(), name='article_update'),
    url(r'article_losses/(?P<pk>[0-9]+)$', add_one_loss, name='article_losses'),
    #url(r'add_one_loss/(?P<pk>[0-9]+)$', AddOneLossView.as_view(), name='add_one_loss'),
    url(r'^article_detail/(?P<pk>[0-9]+)$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article_delete/(?P<pk>[0-9]+)$', articleDeleteView, name='article_delete'),
    #url(r'^upload_pic/(?P<pk>[0-9]+)$', upload_pic, name='upload_pic'),
    url(r'^handle_pics/$', handle_pictures, name='handle_pics'),
    url(r'^upload_zipics/$', upload_pictures_zip, name='upload_zipics'),
]

cart/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
from inventory.models import Branch, Article
from dashboard.utils import TimeSliceHelper
import logging

logger = logging.getLogger('django')




class Client(models.Model):
    name = models.CharField(_('Last name'), max_length=80)
    first_name = models.CharField(_('First name'), max_length=80)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,20}$',
                                 message="Format: '+999999999'. Maximum 20 chiffres.")
    tel = models.CharField(_('Phone.'), max_length=20, validators=[phone_regex], help_text=_("no spaces between digits please"),
                           null=True, blank=True)

    class Meta:
        unique_together = ['name', 'first_name']
        ordering = ['name']

    def __str__(self):
        return self.first_name + ' ' + self.name

    def get_absolute_url(self):
        return reverse('cart:client', kwargs={'pk': self.pk})


class VenteManager(models.Manager):

    def total_sellings(self, year=None, branch=None, start_date=None, end_date=None):
        helper = TimeSliceHelper(self.model)
        ventes = helper.get_objects(year=year, branch=branch, start_date=start_date, end_date=end_date)
        total = sum(v.montant for v in ventes if v.reglement_termine)
        return total


class Vente(models.Model):
    """Simplistic. Further adds are:
    - le statut: terminé ou pas
    - un lien sur les avances
    - un lien sur une cliente
    """
    branch = models.ForeignKey(Branch, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    montant = models.DecimalField(_('montant'), max_digits=20, decimal_places=2, default=0)
    client  = models.ForeignKey(Client, null=True, blank=True, verbose_name=_('Client'), help_text=_("Make the field empty (---) if the customer is not registered."))
    reglement_termine = models.BooleanField(_('Selling closed'), default=False)
    objects = VenteManager()

    class Meta:
        ordering = ['-date']

    def __str__(self):
        titre = "ID: %s / %s / %s / Closed? %s " % (self.pk, self.date, self.montant, self.reglement_termine)
        return titre

    def get_absolute_url(self):
        return reverse('cart:vente', kwargs={'pk': self.pk})

    def total_paiements(self):
        total = 0
        for p in self.paiement_set.all():
            total += p.montant
        return total

    def solde_paiements(self):
        return self.montant - self.total_paiements()



class Paiement(models.Model):
    PAYMENT_MODE = (
        ('C' , 'Cash'),
        ('B' , 'Bank'),
    )

    date    = models.DateTimeField(default=timezone.now)
    montant = models.DecimalField(_('Amount'), max_digits=20, decimal_places=0, default=0)
    vente   = models.ForeignKey(Vente, verbose_name=_('Selling'))
    payment_mode = models.CharField(max_length=1, choices=PAYMENT_MODE, null=True, blank=True)

    class Meta:
        ordering = ['-date']


    def __str__(self):
        return "Montant: %s / Vente-ID: %s" % (self.montant, self.vente.pk)

    def get_absolute_url(self):
        return reverse('cart:paiement', kwargs={'pk': self.pk})


class CartItem(models.Model):
    cart_id    = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    quantity   = models.IntegerField(default=1)
    article    = models.ForeignKey(Article, unique=False)
    prix       = models.DecimalField(_('Price'), max_digits=20, decimal_places=0, default=25000)
    vente      = models.ForeignKey(Vente, null=True, verbose_name=_('Selling')) # par défaut si une vente est effacée, ses cart_item aussi
    # Si le panier est validé pour une vente, ce dernier est vidé. (session_id effacé)
    # Pour retrouver les éléments il faut utiliser Vente-ID
    cart_complete = models.BooleanField(default=False, verbose_name=_('Cart validated'))

    class Meta:
        db_table = 'cart_items'
        ordering = ['date_added']

    def total(self):
        return self.quantity * self.prix

    def update_article_quantity(self):
        logger.info("CartItem.update_article_quantity: Article quantity before update {0}".format(self.article.quantity))
        self.article.quantity = self.article.quantity - self.quantity
        logger.info("After update: {0}".format(self.article.quantity))
        self.article.save()

    @property
    def nom(self):
        return self.article.name


    def get_absolute_url(self):
        return self.article.get_absolute_url()


    def augment_quantity(self, quantity):
        # check if this is possible given 1) the stock available and 2) the actual quantity
        if self.quantity < self.article.quantity:
            self.quantity = self.quantity + int(quantity)
            self.save()

    def set_quantity(self, quantity):
        if quantity <= self.article.quantity and quantity > 0:
            self.quantity = quantity
            self.save()
        else:
            self.quantity = self.article.quantity
            msg = _("Warning: quantity is greater than stock quantity.")
            return msg

    def get_total_of_cart(session_id):
        """
        Select the cart_items for this session_id and sum the total
        of each item.
        :return: the total of cart content
        """
        cart_items = CartItem.objects.filter(cart_id=session_id)
        cart_total_list = [cart_item.total() for cart_item in cart_items]
        return sum(cart_total_list)

    # def get_vente_id(session_id):
    #     cart_items = CartItem.objects.filter(cart_id=session_id)
    #     if cart_items:
    #         return cart_items[0].vente.pk
    #     else:
    #         return None

cart/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import TabHolder, Tab, FormActions
from crispy_forms.layout import Submit, Layout, Fieldset, Field
from django import forms
from django.utils.translation import ugettext_lazy as _
from inventory.models import Branch


from django.shortcuts import reverse
from inventory.models import Article
from .models import Vente, Client, Paiement, CartItem

class VenteCreateForm(forms.ModelForm):
    class Meta:
        model = Vente
        fields = ('branch', 'date', 'client', 'montant')
        widgets = {
            'date': forms.DateTimeInput(
                attrs={'id': 'datetimepicker_vente'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(VenteCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )



class CartItemCreateForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ('quantity', 'article', 'prix')

    def __init__(self, *args, **kwargs):
        super(CartItemCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )


class VenteUpdateForm(forms.ModelForm):
    class Meta:
        model = Vente
        fields = ('branch', 'date', 'client', 'montant', 'reglement_termine')
        widgets = {
            'date': forms.DateTimeInput(
                attrs={'id': 'datetimepicker_vente'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(VenteUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )


class VenteDeleteForm(forms.ModelForm):
    class Meta:
        model = Vente
        fields = ('date', 'client', 'montant', 'reglement_termine')

    def __init__(self, *args, **kwargs):
        super(VenteDeleteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )


class ClientCreateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'first_name', 'tel')

    def __init__(self, *args, **kwargs):
        super(ClientCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )

class ClientUpdateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'first_name', 'tel')
    def __init__(self, *args, **kwargs):
        super(ClientUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )



class PaiementUpdateForm(forms.ModelForm):
    class Meta:
        model = Paiement
        fields = ('date', 'montant', 'vente', 'payment_mode')

        widgets = {
            'vente': forms.TextInput(
                attrs={'readonly': 'True'}  # attr 'disabled' causes field is removed from "cleaned_data"
                # which is used in method "clean".
            ),

            'date': forms.DateTimeInput(
                attrs={'id': 'datetimepicker_vente'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(PaiementUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout = Layout(
            'date', 'vente', 'montant', 'payment_mode',
        )
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )


class PaiementCreateForm(forms.Form):

    date = forms.DateTimeField(required=True, widget=forms.DateTimeInput(
        attrs={'id': 'datetimepicker_vente'}
    ))
    montant = forms.DecimalField(required=True, label=_("Amount"))
    # todo: add payment_mode
    payment_mode = forms.ChoiceField(choices=(Paiement.PAYMENT_MODE), required=False, label=_("Payment mode"))


    def __init__(self, *args, **kwargs):
        super(PaiementCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )


    # def clean(self):
    #     cleaned_data = super(PaiementCreateForm, self).clean()
    #     vente_pk = cleaned_data['vente']
    #     montant = cleaned_data['montant']
    #     vente = Vente.objects.get(pk=vente_pk.pk)
    #     if float(montant) > vente.solde_paiements():
    #         #self.add_error('montant', 'Montant dépasse le solde!')
    #         raise forms.ValidationError('Le montant dépasse le solde qui reste à payer!', code='toogreat')
    #     return cleaned_data
    #

cart/templates/cart/cart_content.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}
{% block content %}

<div class="container">
  <h3>{% trans "3th step" %}  <small>{% trans "step-by-step guide" %}</small></h3>
  <h4>{% trans "Enter the selling price" %}</h4>


  <ol>
    <li>{% trans "Enter the price by editing the field 'Edit'" %}</li>
    <li>{% trans "Validate by clicking on the button 'Edit'" %}</li>
    <li>[{% trans "If there are other article to add to the cart, search again for articles." %}]</li>
    <li>{% trans "Got to the selling form by clicking on the button" %} </li>
  </ol>


  <div class="progress">
    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"
         style="width:60%">
    60% {% trans "of the selling process" %}
    </div>
  </div>






<table class="table-condensed">
      <thead>
         <tr>
            <th>{% trans 'Nr' %}</th>
             <th>{% trans "Date added" %}</th>
             <th>{% trans "Action" %}</th>
            <th>{% trans "Title" %}</th>
            <th>{% trans "Available stock quantity" %}</th>
            <th>{% trans "Quantity" %}</th>
            <th>{% trans "Price" %}</th>
            <th></th>
         </tr>
      </thead>

      <tbody>
      {% for item in cart %}
      <tr><td>{{ forloop.counter }}</td>
          <td>{{ item.date_added }}</td>
          <td>
              <form method="POST" action="{% url "cart:remove_item" item.article.pk  %}">
                {% csrf_token %}
                <input type="submit" class="btn btn-warning" value="{% trans "Remove from cart"%}"/>
              </form>
          </td>
          <td><a href="{% url "inventory:article_detail" item.article.pk %}">{{ item.article.name }}</a></td>
          <td title="{% trans "available quantity" %}">{{ item.article.quantity }}</td>
          <td>
            <form method="POST" action="/cart/save_cart_item/{{item.pk}}">
                    {% csrf_token %}
                 <input id="new_quantity" title="Max: {{item.article.quantity}}" type="number" value="{{ item.quantity }}" name="new_quantity" >
          </td>
          <td>
            <input id="new_price" type="number" value="{{ item.prix }}" name="new_price">
          </td>
          <td>
            <input type="submit" class="btn btn-success" value="{% trans "Save" %}"/>
          </td>
        </form>
      </tr>
      {% endfor %}
      <tr>
          <th colspan="6">{% trans "Total of your cart:" %}</th>
          <td id="amount"><strong>{{ cart_total|intcomma }}</strong></td>
      </tr>



    </table>
{% if cart_total %}


<div class="container">
  <p><a class="btn btn-success" href="{% url "cart:checkout" %}">{% trans "To the selling" %}</a> </p>
</div>


{% endif %}

{% endblock %}

cart/templates/cart/clients.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="container">
    <table class="table table-light">
      <thead class="thead-light">
      <tr>
          <th>ID</th>
          <th>{% trans 'Last Name' %}</th>
          <th>{% trans 'First Name' %}</th>
          <th>{% trans 'Phone' %}</th>
          <th>{% trans 'Edit' %}</th>
          <th>{% trans 'Delete' %}</th>
      </tr>
      </thead>

      <tbody>
      {% for a in clients %}
      <tr>
          <td><a href="{% url "cart:client" a.pk %}">{{a.pk}}</a></td>
          <td>{{ a.name }}</td>
          <td>{{ a.first_name }}</td>
          <td>{{ a.tel|default_if_none:"&mdash;" }}</td>
          <td><a href="{% url "cart:client_update" a.pk %}">{% trans 'Edit'%}</a> </td>
          <td>
            <a href="{% url "cart:client_delete" a.pk %}">{% trans 'Delete' %}</a>
          </td>

      </tr>
      {% endfor %}
    </table>
</div>
{% endblock %}

cart/templates/cart/paiement_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% crispy form %}

{% block javascript %}
<script type="text/javascript">

$( function() {
     $.datepicker.setDefaults(
       $.datepicker.regional["fr-CH"]);
     $( '[id="datetimepicker_vente"]' ).datepicker({
       dateFormat: "yy-mm-dd"});
}
);

$(function() {
  $('[id="id_montant"]').html('3333333');
});


 </script>
{% endblock %}

</div>
{% endblock %}

cart/templates/cart/vente.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load humanize %}
{% load i18n %}
{% block content %}

<div class="container">



  {% if vente.reglement_termine == False %}
  <h3>{% trans "Step 5" %}  <small>{% trans "step-by-step guide" %}</small></h3>
  <h4>{% trans "Add a payment (provision or full payment) to the selling" %} {{ vente.pk }}</h4>
  {% endif %}

    <div class="progress">
    {% if vente.paiement_set.all|length > 0 and vente.reglement_termine == False %}
      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"
         style="width:95%">
    95% {% trans "of the selling process" %}
      </div>
    {% elif vente.reglement_termine == True %}
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"
         style="width:100%">
        100% {% trans "selling closed" %}
      </div>
    {% else %}
      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"
         style="width:90%">
    90% {% trans "of the selling process" %}
      </div>
    {% endif %}
    </div>

  {% if vente.paiement_set.all|length == 0 %}

  <form method="GET" action="{% url "cart:paiement_add" vente.pk  %}">
  {% csrf_token %}
  <input type="submit" class="btn btn-warning" value="{% trans "Add a payment" %}"/>
  </form>

  {% elif vente.paiement_set.all|length > 0 and vente.reglement_termine == False %}
  <form method="GET" action="{% url "cart:paiement_add" vente.pk  %}">
  {% csrf_token %}
  <input type="submit" class="btn btn-warning" value="{% trans 'Add a payment' %}"/>
  </form>
  {% endif %}

<h3>{% trans "Selling Summary" %}</h3>

  <table class="table">
    <tbody>
    <tr>
        <th>{% trans "Selling ID" %}</th>
        <td>{{vente.pk}}</td>
    </tr>

    <tr>

        {% if vente.client %}
        <th>{% trans "Client" %}</th>
        <td>{{vente.client.first_name}} {{vente.client.name}}</td>
        {% endif %}
    </tr>

      <tr>
        <th>{% trans 'Date'%}</th><td>{{vente.date|date:"d/m/y H:i"}}</td>
      </tr>
       <tr>
        <th>{% trans 'Amount' %}</th><td>{{vente.montant|intcomma}}</td>
      </tr>
    </tbody>
  </table>

  <table class="table">
      <thead>
      <tr>
          <th>Article-ID</th>
          <th>{% trans 'Name' %}</th>
          <th>{% trans 'Thumbnail' %}</th>
          <th>{% trans 'Price' %}</th>
          <th>{% trans 'Quantity' %}</th>
      </tr>
      </thead>
      <tbody>
          {% for a in vente.cartitem_set.all %}
          <tr>
              <td><a title="{% trans 'Click to see details' %}" href="/inventory/article_detail/{{a.article.pk}}">{{ a.article.pk }}</td>
              <td>{{a.article.name}}</td>
              {% if a.article.photo %}
              {% thumbnail a.article.photo.path  "50x50" crop="center" as thumbnail %}
              <td><a href="{{ a.article.photo.url }}" alt="image">
                  <img src="{{ thumbnail.url }}" alt="The thumbnail" style="width: {{ thumbnail.width }}">
                  </a>
              </td>
              {% endthumbnail %}
              {% else %}
              <td>{% trans "no thumbnail available" %}</td>
              {% endif %}
              <td>{{a.prix|intcomma}}</td>
              <td>{{a.quantity}}</td>
          </tr>
          {% endfor %}
      </tbody>
  </table>

  <h3>{% trans "Payments' List" %}</h3>
  {% if vente.paiement_set.all|length == 0 %}
<div class="info alert-danger">
<p>{% trans "No saved payment" %}!</p>
</div>
{% endif %}

  {% if vente.paiement_set.all|length > 0 %}

    <table class="table">
        <thead>
        <tr>
            <th>{% trans 'Nr' %}</th>
            <th>{% trans 'Date' %}</th>
            <th>{% trans 'Amount' %}</th>
            <th>{% trans 'Type' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for p in vente.paiement_set.all %}
        <tr><td>{{forloop.counter}}</td>  <td>{{p.date|date:"D d/m/y"}}</td><td>{{p.montant|intcomma}}</td>
          <td>{{p.get_payment_mode_display|default_if_none:"&mdash;"}}</td>
        </tr>
        {% endfor %}
        <tr>
            <th colspan="2">Total</th>
            <td colspan="2">{{ vente.total_paiements|intcomma }}</td>
        </tr>
        <tr>
            <th colspan="2">{% trans "Reduced price" %}</th>
            <td colspan="2">{{ vente.solde_paiements|intcomma }}</td>
        </tr>
        </tbody>
    </table>
  {% endif %}


<h3>{% trans "Edit the selling" %}</h3>


  <form method="GET" action="{% url "cart:vente_update" vente.pk  %}">
       {% csrf_token %}
       <input type="submit" class="btn btn-danger" value="{% trans 'Edit the selling' %}"/>
    </form>


</div>

{% endblock %}

{% block footernav %}

{% endblock %}