cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^add_item/(?P<pk>[0-9]+)$', views.add_cart_item, name='add_item'),
    url(r'^cart_content/$', views.CartView.as_view(), name='cart_content'),
    url(r'^save_cart_item/(?P<pk>[0-9]+)$', views.save_cart_item, name='save_cart_item'),
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^remove_item/(?P<pk>[0-9]+)$', views.remove_cart_item, name='remove_item'),
    url(r'^remove_item_from_vente/(?P<pk>[0-9]+)$', views.remove_article_from_vente_and_update_article_quantity,
        name='remove_article_from_vente'),
    url(r'^edit_price/(?P<pk>[0-9]+)$', views.edit_price, name='edit_price'),
    url(r'^edit_quantity/(?P<pk>[0-9]+)$', views.edit_quantity, name='edit_quantity'),
    url(r'^vente/(?P<pk>[0-9]+)$', views.VenteDetail.as_view(), name='vente'),
    url(r'^vente_update/(?P<pk>[0-9]+)$', views.VenteUpdateView.as_view(), name='vente_update'),
    #url(r'^vente_delete/(?P<pk>[0-9]+)$', views.VenteDeleteView.as_view(), name='vente_delete'),
    url(r'^vente_delete/(?P<pk>[0-9]+)$', views.vente_delete, name='vente_delete'),
    url(r'^ventes/$', views.VenteListView.as_view(), name='ventes'),
    url(r'^clients/$', views.ClientListView.as_view(), name='clients'),
    url(r'^client/(?P<pk>[0-9]+)$', views.ClientDetailView.as_view(), name='client'),
    url(r'^client_update/(?P<pk>[0-9]+)$', views.ClientUpdateView.as_view(), name='client_update'),
    url(r'^client_delete/(?P<pk>[0-9]+)$', views.ClientDeleteView.as_view(), name='client_delete'),
    url(r'^client_create/$', views.ClientCreateView.as_view(), name='client_create'),
    url(r'^paiements/$', views.PaiementListView.as_view(), name='paiements'),
    url(r'^paiement_add/(?P<vente_pk>[0-9]+)$', views.add_paiement, name='paiement_add'),
    url(r'^paiement/(?P<pk>[0-9]+)$', views.PaiementDetailView.as_view(), name='paiement'),
    url(r'^paiement_update/(?P<pk>[0-9]+)$', views.PaiementUpdateView.as_view(), name='paiement_update'),
    ]

inventory/urls.py
from django.conf.urls import url
from .views import ArticleDetailView, articles, ArticleUpdateView, articleDeleteView, ArticlesByPicturesView
from .views import ArrivalListView, ArrivalUpdateView, ArrivalCreateView, ArrivalDetailView, ArrivalDeleteView
from .views import handle_pictures, upload_pictures_zip, CategoryCreateView, CategoryUpdateView, CategoryListView
from .views import CategoryDetailView, CategoryDeleteView
from .views import add_one_loss, BranchCreateView, BranchDetailView, BranchDeleteView
from .views import BranchListView, BranchEditView
from .views import LossDeleteView, LossesListView, LossUpdateView, LossDetailView


app_name = 'inventory'


urlpatterns = [
    url(r'^arrival_create/$', ArrivalCreateView.as_view(), name='arrival_create'),
    url(r'^arrival_detail/(?P<pk>[0-9]+)$', ArrivalDetailView.as_view(), name='arrival_detail'),
    url(r'^arrival_update/(?P<pk>[0-9]+)$', ArrivalUpdateView.as_view(), name='arrival_update'),
    url(r'^arrival_delete/(?P<pk>[0-9]+)$', ArrivalDeleteView.as_view(), name='arrival_delete'),
    url(r'^arrivals/$', ArrivalListView.as_view(), name='arrivals'),
    url(r'^categories/$', CategoryListView.as_view(), name='categories'),
    url(r'^category_update/(?P<pk>[0-9]+)$', CategoryUpdateView.as_view(), name='category_update'),
    url(r'^category_create/$', CategoryCreateView.as_view(), name='category_create'),
    url(r'^category_detail/(?P<pk>[0-9]+)$', CategoryDetailView.as_view(), name='category_detail'),
    url(r'^category_delete/(?P<pk>[0-9]+)$', CategoryDeleteView.as_view(), name='category_delete'),
    url('articles/', articles, name='articles'),
    url(r'articles_by_pictures/$', ArticlesByPicturesView.as_view(), name='articles_by_pictures'),

    url(r'^loss_delete/(?P<pk>[0-9]+)$', LossDeleteView.as_view(), name='loss_delete'),
    url(r'^loss_update/(?P<pk>[0-9]+)$', LossUpdateView.as_view(), name='loss_update'),
    url(r'^loss_detail/(?P<pk>[0-9]+)$', LossDetailView.as_view(), name='loss_detail'),
    url(r'^losses/$', LossesListView.as_view(), name='losses'),

    url('branches/', BranchListView.as_view(), name='branches'),
    url('branch_create/$', BranchCreateView.as_view(), name='branch_create'),
    url('branch_detail/(?P<pk>[0-9]+)$', BranchDetailView.as_view(), name='branch_detail'),
    url('branch_delete/(?P<pk>[0-9]+)$', BranchDeleteView.as_view(), name='branch_delete'),
    url('branch_update/(?P<pk>[0-9]+)$', BranchEditView.as_view(), name='branch_update'),

    url(r'article_update/(?P<pk>[0-9]+)$', ArticleUpdateView.as_view(), name='article_update'),
    url(r'article_losses/(?P<pk>[0-9]+)$', add_one_loss, name='article_losses'),
    #url(r'add_one_loss/(?P<pk>[0-9]+)$', AddOneLossView.as_view(), name='add_one_loss'),
    url(r'^article_detail/(?P<pk>[0-9]+)$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article_delete/(?P<pk>[0-9]+)$', articleDeleteView, name='article_delete'),
    #url(r'^upload_pic/(?P<pk>[0-9]+)$', upload_pic, name='upload_pic'),
    url(r'^handle_pics/$', handle_pictures, name='handle_pics'),
    url(r'^upload_zipics/$', upload_pictures_zip, name='upload_zipics'),
]

inventory/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import logging
import os
from datetime import date
from dashboard.utils import TimeSliceHelper


logger = logging.getLogger('django')

class Enterprise(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Employee(models.Model):
    """
    Every user is an employee of one enterprise.

    The articles tables (derived from Product: Accessory, Clothes and Shoe)
     are bound to one enterprise with the help of the foreign key 'Product.product_owner'

    One user may work only with the articles belonging to his/her enterprise.

    The belonging of this user to the enterprise is expressed with the
    foreign key 'Employee.enterprise'.

    Conclusion: the employee has access permission only to the articles of her enterprise.

    Process to create one employee:

    a) create one user
    b) create one enterprise
    c) create one Employee with foreign keys to user and enterprise
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    enterprise = models.ForeignKey(Enterprise, related_name="employees")

    def get_enterprise_of_current_user(user):
        """
        A class helper method used by the abstract products.forms.ProductCreateForm.
        :param user: the request.user used to retrieve one Employee instance.
        :return: the Enterprise instance of the Employee instance.
        """
        if Employee.objects.filter(user=user).exists():
            employee = Employee.objects.get(user=user)
            return employee.enterprise

    def is_current_user_employee(user):
        if Employee.objects.filter(user=user).exists():
            employee = Employee.objects.get(user=user)
            return employee.enterprise != None
        else:
            return False


    def __str__(self):
        if self.enterprise is not None:
            return self.user.username + ': ' + str(self.enterprise)
        else:
            return self.user.username


class Arrivage(models.Model):
    nom = models.CharField(max_length=50, unique=True)
    date_arrivee = models.DateField(_('Arrival Date'))
    #proprietaire = models.ForeignKey(Enterprise, null=True)

    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse('inventory:arrival_detail', kwargs={'pk': self.pk})


class Frais(models.Model):
    montant = models.DecimalField(max_digits=20, decimal_places=2)
    objet = models.TextField()
    date = models.DateField()
    entreprise = models.ForeignKey(Enterprise, null=True)
    arrivage = models.ForeignKey(Arrivage, null=True)

    def __str__(self):
        return self.objet + ': ' + str(self.montant)

    class Meta:
        verbose_name_plural = 'Frais'

class Category(models.Model):
    name = models.CharField(_('Category'), max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse('inventory:category_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Branch(models.Model):
    """One enterprise can have multiple branches.
    For sample one shop and one production unit.
    """
    name = models.CharField(_('Name'), max_length=100, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('inventory:branch_detail', kwargs={'pk' : self.pk})

    class Meta:
        ordering = ['name']
        verbose_name = _('Branch')


class ArticleManager(models.Manager):

    def total_purchasing_price(self, branch=None, year=None, start_date=None, end_date=None):
        total = 0
        helper = TimeSliceHelper(Article)
        articles = helper.get_objects(year=year, branch=branch, start_date=start_date, end_date=end_date)
        total = sum(a.purchasing_price for a in articles)
        return total

    def total_losses(self, branch=None, year=None, start_date=None, end_date=None):
        """Return how much money was lost because broken articles or other cause."""
        helper = TimeSliceHelper(Article)
        articles = helper.get_objects(year=year, branch=branch, start_date=start_date, end_date=end_date)
        total = sum(a.get_amount_losses for a in articles)
        return total





class Article(models.Model):
    """Base for an article containing the only required fields: photo."""

    solde_choices = (
        ('N', _('-')),
        ('S', _('en solde')),
    )

    branch = models.ForeignKey(Branch, null=True, blank=True, on_delete=models.SET_NULL)
    photo = models.ImageField(upload_to='articles', null=True, blank=True, unique=True)
    purchasing_price = models.DecimalField(_('Purchasing price'), max_digits=10, decimal_places=2, null=True, blank=True,
                                           default=0)
    selling_price    = models.DecimalField(_('Selling price'), max_digits=10, decimal_places=2, null=True, blank=True,
                                           default=0)
    name  = models.CharField(_('Name'), max_length=100, null=True, blank=True, default=_('n.d.'))
    category = models.ForeignKey(Category, null=True, blank=True, verbose_name=_('Category'))
    description = models.TextField(_('Description'), null=True, blank=True, default=_('n.d.'))
    date_added  = models.DateField(default=date.today, null=True)
    # initial quantity when article is added to the inventory
    initial_quantity = models.IntegerField(_('Initial quantity'), default=1, null=True)
    quantity = models.PositiveSmallIntegerField(_('Quantity'), default=1)
    # losses  = models.PositiveSmallIntegerField(_('Losses'), default=0)
    # amount_losses = models.DecimalField(_('Money lost'), max_digits=10, decimal_places=2, null=True, blank=True,
    #                                        default=0)
    solde = models.CharField(_("en solde"), max_length=1, choices=solde_choices, default='N')
    arrival = models.ForeignKey(Arrivage, null=True, on_delete=models.SET_NULL)
    notes = models.TextField(_("Notes"), null=True, blank=True, default=_('n.d.'))

    objects = ArticleManager()

    class Meta:
        verbose_name = _('Article with minimal data')
        ordering = ['pk']

    def delete(self):
        """Work fine for article indivdually deleted but not for bulk delete. Admin action required."""
        try:
            os.unlink(self.photo.path)
        except (ValueError, FileNotFoundError):
            logger.warning('No deletion of photo because no photo file found. (delete method within model Article).')

        super(Article, self).delete()



    def get_absolute_url(self):
        return reverse('inventory:article_detail', kwargs={'pk': self.pk})

    @property
    def get_amount_losses(self):
        """Return total money lost"""
        return Losses.objects.total_losses_for_article(self)

    @property
    def losses(self):
        """Return total quantity of losses for this article"""
        return Losses.objects.total_losses_quantity_for_article(self)

    @property
    def get_total_quantity_losses(self):
        """Return total quantity of losses for this article"""
        return Losses.objects.total_losses_quantity_for_article(self)



    def __str__(self):
        s = "Name: {0}\n Branch: {1}\n Arrival: {2}\n Category: {3}\n Quantity: {4}\n Purch. price: {5}\n Selling price: {6}\n Date added: {7}".format(
            self.name,
            self.branch,
            self.arrival,
            self.category,
            self.quantity,
            self.purchasing_price,
            self.selling_price,
            self.date_added
        )
        return s


class LossesManager(models.Manager):

    def total_costs(self, branch=None, year=None, start_date=None, end_date=None):
        """Return how much money was lost because broken articles or other cause."""
        helper = TimeSliceHelper(Losses)
        losses = helper.get_objects(branch=branch, year=year, start_date=start_date, end_date=end_date)
        total = sum(a.amount_losses for a in losses)
        return total

    def total_quantity(self, branch=None, year=None, start_date=None, end_date=None):
        helper = TimeSliceHelper(Losses)
        losses = helper.get_objects(branch=branch, year=year, start_date=start_date, end_date=end_date)
        total = sum(a.losses for a in losses)
        return total

    def total_losses_for_article(self, article):
        """
        :param article:
        :return: total of money lost in losses for this article
        """
        qs = Losses.objects.filter(article=article)
        total = sum(a.amount_losses for a in qs)
        return total

    def total_losses_quantity_for_article(self, article):
        """

        :param article:
        :return: total quantity of losses for this article
        """
        qs = Losses.objects.filter(article=article)
        total = sum(a.losses for a in qs)
        return total



class Losses(models.Model):
    """Losses of one article because article was broken, stolen or other cause, event not sold.
    More: it can be losses not related to articles or even to a branch.
    """
    losses  = models.PositiveSmallIntegerField(_('Losses'), default=0)
    amount_losses = models.DecimalField(_('Money lost'), max_digits=10, decimal_places=2, null=True, blank=True,
                                           default=0)
    date = models.DateField(default=date.today, null=True, blank=True)
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, null=True, related_name='Pertes')
    loss_type    = models.CharField(_("Type of loss"), max_length=100, help_text=_("Cause of the loss: not sold, broken, etc."),
                                    null=True, blank=True)

    branch = models.ForeignKey(Branch, null=True, blank=True, on_delete=models.SET_NULL)
    note = models.TextField(_('Note'), blank=True, null=True)

inventory/templates/inventory/arrival_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% crispy form %}
</div>
{% endblock %}
{% block javascript %}
<script type="text/javascript">

$( function() {
     $.datepicker.setDefaults(
       $.datepicker.regional["es"]);
     $( '[id="datetimepicker_arrival"]' ).datepicker({
       dateFormat: "yy-mm-dd"});
}
);


  </script>
{% endblock %}

inventory/templates/inventory/arrival_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load thumbnail %}
{% block content %}
<p>
<div class="container">



  <h2>{% trans "Arrival Details" %}</h2>

  <table class="table">
    <tbody>

      <tr>
        <th>{% trans "Date" %}</th><td>{{arrival.date_arrivee}}</td>
      </tr>

      <tr>
          <th>{% trans "Name" %}</th>
        <td>{{arrival.nom}}</td>
      </tr>
      <tr>
          <th>{% trans "Owner" %}</th>
        <td>{{arrival.proprietaire}}</td>
      </tr>

    </tbody>
  </table>

</div>
</p>


{% endblock %}

{% block footernav %}

{% endblock %}

inventory/templates/inventory/arrivals.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load humanize %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}
<div class="container">

    <table class="table table-light">
      <thead class="thead-light">
      <tr>
          <th>{% trans 'Nr.' %}</th>
          <th>{% trans 'Name' %}</th>
          <th>{% trans "Creation Date" %}</th>
          <th>{% trans "Delete" %}</th>
      </tr>
      </thead>


      <tbody>
      {% for a in arrivals %}
      <tr>
        <td><a title="{% trans 'Click to see details' %}" href="/inventory/arrival_update/{{a.pk}}"> {{ forloop.counter}}</a></td>
          <td>{{ a.nom}}</td>
          <td>{{ a.date_arrivee|date:'d.m.Y' }}</td>
          <td><a href="{% url "inventory:arrival_delete" a.pk %}">{% trans 'Delete' %}</a> </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>

{% endblock %}
{% block footer %}
{% endblock %}

inventory/templates/inventory/articles.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load humanize %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}
<div class="container">

  <div class="panel panel-info">
    <div class="panel-heading">
      <a href="#summary" data-toggle="collapse">{% trans "Summary without filters" %}</a>
    </div>

    <div id="summary" class="panel-collapse collapse">
      <div class="panel-body">
        <table class="table">
          <thead>
          <tr>
            <th colspan="2"></th>
            <th>{% trans "Count" %}</th>
            <th>&percnt;</th>
          </tr>
          </thead>
          <tbody>
          <tr class="row">
            <th  class="col-xs-2">{% trans "Total articles" %}</th>
            <td class="col-xs-1">{{summary.total}}</td>
            <td class="col-xs-9">&ndash;</td>
          </tr>
          <tr class="row">
            <th class="col-xs-2">{% trans "Out of stock" %}</th>
            <td class="col-xs-1">{{summary.quantity_zero}}</td>
            <td class="col-xs-9">
              <div class='progress'>
                <div class="progress-bar progress-bar-danger" role="progressbar"
                     style="width: {{summary.quantity_zero_percent}}%;">
                  {{summary.quantity_zero_percent}} %
                </div>
              </div>
            </td>
          </tr>
          <tr class="row">
            <th class="col-xs-2">{% trans "Reduced price" %}</th>
            <td class="col-xs-1">{{summary.reduced}} </td>
            <td class="col-xs-9">
              <div class='progress'>
                <div title="{{summary.reduced_percent}} %" class="progress-bar progress-bar-info" role="progressbar"
                     style="width: {{summary.reduced_percent}}%;">
                  {{summary.reduced_percent}} %
                </div>
              </div>
            </td>
          </tr>
          <tr class="row">
            <th class="col-xs-2">{% trans "Without category" %}</th>
            <td class="col-xs-1">{{summary.no_category}}</td>
            <td class="col-xs-9">
              <div class='progress'>
                <div class="progress-bar progress-bar-warning" role="progressbar" style="width: {{summary.no_category_percent}}%;">
                  {{summary.no_category_percent}}%
                </div>
              </div>
            </td>
          </tr>
          <tr class="row">
            <th class="col-xs-2">{% trans "Without name" %}</th>
            <td class="col-xs-1">{{summary.no_name}}</td>
            <td class="col-xs-9">
              <div class='progress'>
                <div title="{{summary.no_name}}" class="progress-bar progress-bar-warning" role="progressbar"
                     style="width: {{summary.no_name_percent}}%;">
                      {{summary.no_name_percent}}%
                </div>
            </div>
            </td>
          </tr>
          <tr class="row">
              <th class="col-xs-2">{% trans "Without selling price" %}</th>
              <td class="col-xs-1">{{summary.selling_price_zero}}</td>
              <td class="col-xs-9">
                <div class='progress'>
                  <div title="{{summary.no_name}}" class="progress-bar progress-bar-warning" role="progressbar"
                     style="width: {{summary.no_selling_price_percent}}%;">
                      {{summary.no_selling_price_percent}}%
                  </div>
                </div>
              </td>
          </tr>
          <tr class="row">
            <th class="col-xs-2">{% trans "Without purchasing price" %}</th>
            <td class="col-xs-1">{{summary.purchasing_price_zero}}</td>
            <td class="col-xs-9">
              <div class='progress'>
                <div title="{{summary.no_name}}" class="progress-bar progress-bar-warning" role="progressbar"
                     style="width: {{summary.no_purchasing_price_percent}}%;">
                  {{summary.no_purchasing_price_percent}}%
                </div>
              </div>
            </td>
          </tr>
          </tbody>
        </table>
        </div>
      </div>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <a href="#selling_guide" data-toggle="collapse">{% trans "1st step" %}  <small>{% trans "step-by-step guide" %}</small></a>
    </div>
    <div id="selling_guide" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>{% trans "Search one article to register a selling" %}</h4>
        <ol>
          <li>{% trans "Search the article with the filter" %}; ({% trans "enter your search criteria and click on the search button" %}
            <strong>{% trans "Search" %}</strong>)</li>
          <li>{% trans "Go to the article by clicking on the link <strong>Name</strong>"%};</li>
        </ol>
        <div class="progress">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"
             style="width:20%">
        20% {% trans "of the selling process" %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <a href="#filter" data-toggle="collapse">{% trans "Filter" %}</a>
    </div>
    <div id="filter" class="panel-collapse collapse">
      <div class="panel-body">
        <form action="" method="get">
        <div class="well well-md" id="filtre_articles">

          <div class="row">
            <div class="form-group col-xs-3 col-sm-3">
              {{filter.form.id.label_tag}}
              {% render_field filter.form.id class="form-control" %}
            </div>
            <div class="form-group col-xs-9 col-sm-9">
              <strong>{% trans "Part of branch" %}:</strong>
              {% render_field filter.form.branch__name__icontains  class="form-control" %}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "Part of the category's name " %}:</strong>
              {% render_field filter.form.category__name__icontains  class="form-control" %}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "Part of the name" %}:</strong>
              {% render_field filter.form.name__icontains  class="form-control" %}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "Selling Price greater than" %}:</strong>
              {% render_field filter.form.selling_price__gt class="form-control" %}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "reduced price" %}:</strong>
              {% render_field filter.form.solde  class="form-control" %}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "Quantity greater than" %}:</strong>
              {% render_field filter.form.quantity__gt  class="form-control" %}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "Part of Arrival's Name" %}:</strong>
              {% render_field filter.form.arrival__nom__icontains  class="form-control" %}
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "Purchasing Price Greater than" %}:</strong>
              {% render_field filter.form.purchasing_price__gt class="form-control" %}
            </div>
          </div>

          <div class="row">
            <div class="form-group col-xs-12 col-sm-12">
              <strong>{% trans "Losses greater/equal than" %}:</strong>
              {% render_field filter.form.losses class="form-control" %}
            </div>
          </div>


          <div class="row">
            <div class="col-xs-3 col-sm-3">
              <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-search"></span> {% trans "Search" %}
              </button>
            </div>
          </div>
        </div>
  </form>
      </div>
    </div>
  </div>

<h3>{{count}} {% trans "articles found" %}.</h3>

<div class="table-responsive">
    <table class="table table-light">

      <thead class="thead-light">
      <tr>
          <th>{% trans 'Nr.' %}</th>
          <th>{% trans "ID" %}</th>
          <th>{% trans 'Thumbnail' %}</th>
          <th>{% trans 'Purchasing price' %}</th>
          <th>{% trans "Selling price" %}</th>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Category" %}</th>
          <th>{% trans "Reduced price?" %}</th>
          <th>{% trans "Quantity" %}</th>
      </tr>
      </thead>


      <tbody>
      {% for a in articles %}
      <tr>
        <td><a title="{% trans 'Click to see details' %}" href="/inventory/article_detail/{{a.pk}}">{{ forloop.counter0|add:start_index}}</a></td>
        <td><a title="{% trans 'Click to see details' %}" href="/inventory/article_detail/{{a.pk}}">{{a.pk}}</a></td>
        {% if a.photo %}
          {% thumbnail a.photo  "50x50" crop="center" as im %}
          <td><a href="{{ a.photo.url }}" alt="picture of {{a.name}}-ID: {{a.pk}}">
              <img src="{{ im.url }}" alt="The thumbnail" style="width: {{ im.width }}">
              </a>
          </td>
          {% empty %}
          <td>{% trans "no pic found" %}</td>
          {% endthumbnail %}
        {% else %}
          <td>{% trans "no pic found" %}</td>
        {% endif %}
          <td>{{ a.purchasing_price|intcomma}}</td>
          <td>{{ a.selling_price|intcomma }}</td>
          <td>{{ a.name|default_if_none:"n.d." }}</td>
          <td>{{ a.category|default_if_none:"n.d." }}</td>
          <td>{{ a.get_solde_display }}</td>
          {% if a.quantity > 0 %}
           <td><span class="badge progress-bar-info">{{ a.quantity }}</span></td>
          {% else %}
          <td><span class="badge progress-bar-warning">{{ a.quantity }}</span></td>
          {% endif %}
      </tr>

      {% endfor %}
      </tbody>
    </table>
</div>


  {% if articles.has_other_pages %}
  <ul class="pagination">
    {% if articles.has_previous %}
      <li><a href="?page={{ articles.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if articles.has_next %}
    <li><a href="?page={{ articles.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
{% endblock %}
{% block footer %}
{% endblock %}