cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'

urlpatterns = [
    url(r'^add_item/(?P<pk>[0-9]+)$', views.add_cart_item, name='add_item'),
    url(r'^cart_content/$', views.CartView.as_view(), name='cart_content'),
    url(r'^save_cart_item/(?P<pk>[0-9]+)$', views.save_cart_item, name='save_cart_item'),
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^remove_item/(?P<pk>[0-9]+)$', views.remove_cart_item, name='remove_item'),
    url(r'^remove_item_from_vente/(?P<pk>[0-9]+)$', views.remove_article_from_vente_and_update_article_quantity,
        name='remove_article_from_vente'),
    url(r'^edit_price/(?P<pk>[0-9]+)$', views.edit_price, name='edit_price'),
    url(r'^edit_quantity/(?P<pk>[0-9]+)$', views.edit_quantity, name='edit_quantity'),
    url(r'^vente/(?P<pk>[0-9]+)$', views.VenteDetail.as_view(), name='vente'),
    url(r'^vente_update/(?P<pk>[0-9]+)$', views.VenteUpdateView.as_view(), name='vente_update'),
    #url(r'^vente_delete/(?P<pk>[0-9]+)$', views.VenteDeleteView.as_view(), name='vente_delete'),
    url(r'^vente_delete/(?P<pk>[0-9]+)$', views.vente_delete, name='vente_delete'),
    url(r'^ventes/$', views.VenteListView.as_view(), name='ventes'),
    url(r'^clients/$', views.ClientListView.as_view(), name='clients'),
    url(r'^client/(?P<pk>[0-9]+)$', views.ClientDetailView.as_view(), name='client'),
    url(r'^client_update/(?P<pk>[0-9]+)$', views.ClientUpdateView.as_view(), name='client_update'),
    url(r'^client_delete/(?P<pk>[0-9]+)$', views.ClientDeleteView.as_view(), name='client_delete'),
    url(r'^client_create/$', views.ClientCreateView.as_view(), name='client_create'),
    url(r'^paiements/$', views.PaiementListView.as_view(), name='paiements'),
    url(r'^paiement_add/(?P<vente_pk>[0-9]+)$', views.add_paiement, name='paiement_add'),
    url(r'^paiement/(?P<pk>[0-9]+)$', views.PaiementDetailView.as_view(), name='paiement'),
    url(r'^paiement_update/(?P<pk>[0-9]+)$', views.PaiementUpdateView.as_view(), name='paiement_update'),
    ]

costs/urls.py
from django.conf.urls import url
from . import views


app_name = 'costs'

urlpatterns = [
    url(r'^category_create/$', views.CategoryCreateView.as_view(), name='category_create'),
    url(r'^category_details/(?P<pk>[0-9]+)$', views.CategoryDetailView.as_view(), name='category_details'),
    url(r'^category_update/(?P<pk>[0-9]+)$', views.CategoryUpdateView.as_view(), name='category_update'),
    url(r'^category_delete/(?P<pk>[0-9]+)$', views.CategoryDeleteView.as_view(), name='category_delete'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='categories'),
    url(r'^enterprise_create/$', views.EnterpriseCreateView.as_view(), name='enterprise_create'),
    url(r'^enterprise_details/(?P<pk>[0-9]+)$', views.EnterpriseDetailView.as_view(), name='enterprise_details'),
    url(r'^enterprise_update/(?P<pk>[0-9]+)$', views.EnterpriseUpdateView.as_view(), name='enterprise_update'),
    url(r'^enterprise_delete/(?P<pk>[0-9]+)$', views.EnterpriseDeleteView.as_view(), name='enterprise_delete'),
    url(r'^enterprises/$', views.EnterpriseListView.as_view(), name='enterprises'),
    url(r'^costs_create/$', views.CostsCreateView.as_view(), name='costs_create'),
    url(r'^costs/$', views.CostsListView.as_view(), name='costs'),
    url(r'^costs_branch/(?P<pk>[0-9]+)$', views.CostsPerBranch.as_view(), name='costs_branch'),
    url(r'^costs_details/(?P<pk>[0-9]+)$', views.CostsDetailView.as_view(), name='costs_details'),
    url(r'^costs_update/(?P<pk>[0-9]+)$', views.CostsUpdateView.as_view(), name='costs_update'),
    url(r'^costs_delete/(?P<pk>[0-9]+)$', views.CostsDeleteView.as_view(), name='costs_delete'),
    ]

costs/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import ugettext_lazy as _
from inventory.models import Article, Branch
from cart.models import Vente
from dashboard.utils import TimeSliceHelper
from datetime import date

class Enterprise(models.Model):
    """Or a better name could be 'Provider'."""
    name = models.CharField(_('name'), max_length=80, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        reverse('costs:enterprise_details', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['name']
        verbose_name = _('Enterprise')


class Category(models.Model):
    name = models.CharField(_('name'), max_length=100, unique=True)

    def get_absolute_url(self):
        reverse('costs:category_details', kwargs={'pk': self.pk})


    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('Categories')
        verbose_name = _('Category')
        ordering = ['name']


class CostsManager(models.Manager):

    def total_costs(self, year=None, branch=None, start_date = None, end_date=None):
        helper = TimeSliceHelper(self.model)
        costs = helper.get_objects(year=year, branch=branch, start_date=start_date, end_date=end_date)
        total = sum(c.amount for c in costs)
        return total

    def grand_total(self, branch=None, year=None, start_date = None, end_date=None):
        """Sum of costs + sum of Articles' purchasing price.
        """
        helper = TimeSliceHelper(Article)
        articles = helper.get_objects(year=year, branch=branch, start_date=start_date, end_date=end_date)
        purchasing_price = sum(a.purchasing_price for a in articles)
        return purchasing_price + self.total_costs(branch=branch, year=year, start_date=start_date, end_date=end_date)

    def get_balance(self, branch=None, year=None, start_date = None, end_date=None):
        """
        Ventes minus (purchases + costs). The losses are not taken in account.
        Purchases are taken from Article.objects.total_purchasing_price method.
        :return: Ventes - (purchases + costs)
        """
        return Vente.objects.total_sellings(branch=branch, year=year, start_date = start_date, end_date=end_date) - \
               self.grand_total(branch=branch, year=year, start_date = start_date, end_date=end_date)


class Costs(models.Model):
    branch = models.ForeignKey(Branch, null=True, blank=True, verbose_name=_('Branch'))
    creation_date = models.DateField(_('Creation date'), default=date.today, blank=True)
    category = models.ForeignKey(Category, verbose_name=_('Category'))
    amount = models.DecimalField(_('Amount'), max_digits=20, decimal_places=2)
    name   = models.CharField(_('Name'), max_length=200, help_text=_('short description'), blank=True, null=True)
    note   = models.TextField(_('Note'), blank=True, null=True)
    enterprise = models.ForeignKey(Enterprise, blank=True, null=True, verbose_name=_('Enterprise'))
    billing_date = models.DateField(_('Billing Date'), default=date.today, blank=True, null=True, help_text=_('when the bill was created'))
    billing_number = models.CharField(_('Billing Nr'), blank=True, null=True, max_length=200,
                                      help_text=_('the bill reference number'))
    objects = CostsManager()

    def __str__(self):
        return "Amount: %s / Category: %s / Date: %s " % (self.amount, self.category, self.creation_date)


    class Meta:
        verbose_name_plural = _('Costs')
        ordering = ['-billing_date']

costs/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import TabHolder, Tab, FormActions
from crispy_forms.layout import Submit, Layout, Fieldset, Field
from django import forms
from .models import Costs, Category, Enterprise


class CostsCreateForm(forms.ModelForm):
    class Meta:
        model = Costs
        fields = ('branch', 'name', 'amount', 'category', 'note', 'enterprise', 'billing_date', 'billing_number' )
        widgets = {
            'billing_date': forms.DateInput(
                attrs={'id': 'datetimepicker_es'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(CostsCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )

class CostsUpdateForm(forms.ModelForm):
    class Meta:
        model = Costs
        fields = ('creation_date', 'branch', 'name', 'amount', 'category', 'note', 'enterprise', 'billing_date', 'billing_number' )
        widgets = {
            'billing_date': forms.DateInput(
                attrs={'id': 'datetimepicker_es_update'}
            ),
            'creation_date': forms.DateInput(
                attrs={'id': 'datetimepicker_es'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(CostsUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )



class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(CategoryCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )

class CategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(CategoryUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )



class EnterpriseCreateForm(forms.ModelForm):
    class Meta:
        model = Enterprise
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(EnterpriseCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )


class EnterpriseUpdateForm(forms.ModelForm):
    class Meta:
        model = Enterprise
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(EnterpriseUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "POST"
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.layout.append(
            FormActions(
                Submit('save', 'Submit'),
            )
        )

costs/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, TemplateView
from .models import Category, Enterprise, Costs
from .forms import CategoryCreateForm, CategoryUpdateForm, EnterpriseCreateForm, EnterpriseUpdateForm, CostsCreateForm, CostsUpdateForm
from inventory.models import Branch

@method_decorator(login_required, name='dispatch')
class CategoryDetailView(DetailView):
    model = Category
    template_name = 'costs/category_details.html'
    context_object_name = 'category'

@method_decorator(login_required, name='dispatch')
class CategoryCreateView(CreateView):
    model = Category
    template_name = 'costs/category_create.html'
    context_object_name = 'category'
    form_class = CategoryCreateForm
    success_url = reverse_lazy('costs:categories')

@method_decorator(login_required, name='dispatch')
class CategoryListView(ListView):
    model = Category
    template_name = 'costs/categories.html'
    context_object_name = 'categories'

@method_decorator(login_required, name='dispatch')
class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'costs/category_update.html'
    context_object_name = 'category'
    form_class = CategoryUpdateForm

    def get_success_url(self):
        return '/costs/category_details/%s' % self.object.pk

@method_decorator(login_required, name='dispatch')
class CategoryDeleteView(DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'costs/category_delete.html'
    success_url = reverse_lazy('costs:categories')

@method_decorator(login_required, name='dispatch')
class EnterpriseCreateView(CreateView):
    model = Enterprise
    template_name = 'costs/enterprise_create.html'
    context_object_name = 'enterprise'
    form_class = EnterpriseCreateForm

    def get_success_url(self):
        return '/costs/enterprises'

@method_decorator(login_required, name='dispatch')
class EnterpriseDetailView(DetailView):
    model = Enterprise
    template_name = 'costs/enterprise_details.html'
    context_object_name = 'enterprise'

@method_decorator(login_required, name='dispatch')
class EnterpriseListView(ListView):
    model = Enterprise
    template_name = 'costs/enterprises.html'
    context_object_name = 'enterprises'

@method_decorator(login_required, name='dispatch')
class EnterpriseUpdateView(UpdateView):
    model = Enterprise
    template_name = 'costs/enterprise_update.html'
    context_object_name = 'enterprise'
    form_class = EnterpriseUpdateForm

    def get_success_url(self):
        return '/costs/enterprise_details/%s' % self.object.pk

@method_decorator(login_required, name='dispatch')
class EnterpriseDeleteView(DeleteView):
    model = Enterprise
    template_name = 'costs/enterprise_delete.html'
    context_object_name = 'enterprise'
    success_url = reverse_lazy('costs:enterprises')

@method_decorator(login_required, name='dispatch')
class CostsCreateView(CreateView):
    model = Costs
    template_name = 'costs/costs_create.html'
    context_object_name = 'cost'
    success_url = reverse_lazy('costs:costs')
    form_class = CostsCreateForm

@method_decorator(login_required, name='dispatch')
class CostsListView(ListView):
    model = Costs
    template_name = 'costs/costs.html'
    context_object_name = 'costs'

    def get_context_data(self, q=None):
        ctx = super(CostsListView, self).get_context_data()
        q = self.request.GET.get('q')
        if q:
            ctx['option'] = q
            if q.upper() == 'MAIN':
                # costs = Costs.objects.filter(branch=None)
                # total = sum(c.amount for c in costs)
                total = Costs.objects.total_costs(branch='MAIN')
                ctx['total'] = total
            elif q.upper() == 'ALL':
                ctx['total'] = Costs.objects.total_costs()
            else:
                branch = Branch.objects.get(name=q)
                ctx['total'] = Costs.objects.total_costs(branch=branch)
        else:
            ctx['total'] = Costs.objects.total_costs()
        li = [b.name for b in Branch.objects.all()] + ['All', 'Main']
        li.sort()
        ctx['branchs'] = li
        return ctx

    def get_queryset(self):
        queryset = super(CostsListView, self).get_queryset()
        #ctx = super(CostsListView, self).get_context_data()
        q = self.request.GET.get('q')
        if q:
            if q.upper() == 'MAIN':
                queryset = queryset.filter(branch=None)
            elif q.upper() == 'ALL':
                pass
            else:
                queryset = queryset.filter(branch__name__icontains=q)
        return queryset


@method_decorator(login_required, name='dispatch')
class CostsPerBranch(TemplateView):
    template_name = 'costs/costs.html'
    context_object_name = 'costs'

    def get_context_data(self, pk=None):
        if pk:
            costs = Costs.objects.filter(branch=pk)
        else:
            costs = Costs.objects.all()
        context = {'costs' : costs}
        return context

    def get(self, request, pk=None):
        context = self.get_context_data(pk=pk)
        return render(request=request, template_name='costs/costs.html', context=context)


@method_decorator(login_required, name='dispatch')
class CostsDetailView(DetailView):
    model = Costs
    template_name = 'costs/costs_details.html'
    context_object_name = 'costs'

@method_decorator(login_required, name='dispatch')
class CostsUpdateView(UpdateView):
    model = Costs
    template_name = 'costs/costs_update.html'
    context_object_name = 'costs'
    form_class = CostsUpdateForm

    def get_success_url(self):
        return '/costs/costs_details/%s' % self.object.pk

@method_decorator(login_required, name='dispatch')
class CostsDeleteView(DeleteView):
    model = Costs
    template_name = 'costs/costs_delete.html'
    context_object_name = 'costs'
    success_url = reverse_lazy('costs:costs')

costs/templates/costs/categories.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="container">
    <table class="table table-light">
      <thead class="thead-light">
      <tr>
          <th>{% trans 'Name' %}</th>
          <th>{% trans 'Edit' %}</th>
          <th>{% trans 'Delete' %}</th>
      </tr>
      </thead>

      <tbody>
      {% for a in categories %}
      <tr>
          <td>{{ a.name }}</td>
          <td><a href="{% url "costs:category_update" a.pk %}">{% trans 'Edit'%}</a> </td>
          <td><a href="{% url "costs:category_delete" a.pk %}">{% trans 'Delete'%}</a> </td>
      </tr>
      {% endfor %}
    </table>
</div>
{% endblock %}

costs/templates/costs/category_create.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% crispy form %}
</div>
{% endblock %}

costs/templates/costs/category_delete.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <h3>{% trans "Category:" %} <small>{{category.name}}</small></h3>

  <div class="row">
    <div class="col-sm-6">
      <form action="{% url "costs:category_delete" category.pk  %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-danger" type="submit" value="{% trans "Effacer" %}"</input>
      </form>
      </div>
  </div>

</div>
{% endblock %}

costs/templates/costs/category_details.html
{% extends "base.html"%}
{% load static %}
{% load i18n %}
{% block content %}
<p>
<div class="container">



  <h2>{% trans "Details of the costs' category" %}</h2>

  <table class="table">
    <tbody>

      <tr>
        <th>{% trans "Name" %}</th><td>{{category.name}}</td>
      </tr>

    </tbody>
  </table>

</div>
</p>


{% endblock %}

{% block footernav %}

{% endblock %}

costs/templates/costs/category_update.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% crispy form %}
</div>
{% endblock %}

costs/templates/costs/costs.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="container">

  <div class="row">
      <div class="col-xs-8">
         <form id="costs-filter" class="well" action="{% url "costs:costs" %}" method="GET">
           <div class="form-group">
             <label for="select">{% trans "Branch" %}: </label>
             <select id="select" class="form-control" name="q">
               {% for b in branchs %}
                   {% if option == b %}
                   <option selected>{{ b }}</option>
                   {% else %}
                   <option>{{ b }}</option>
                   {% endif %}
               {% endfor %}
             </select>
           </div>
          <div class="form-group">
            <button class="btn btn-primary" type="submit" >{% trans "Filter" %}</button>
          </div>
         </form>
      </div>
    </div>

    <table class="table table-light">
      <thead class="thead-light">
      <tr>
          <th>{% trans 'Nr' %}</th>
          <th>{% trans 'Billing Date' %}</th>
          <th>{% trans 'Branch' %}</th>
          <th>{% trans 'Name' %}</th>
          <th>{% trans 'Category' %}</th>
          <th>{% trans 'Amount' %}</th>
          <th>{% trans 'Edit' %}</th>
          <th>{% trans 'Delete' %}</th>
      </tr>
      </thead>

      <tbody>
      {% for a in costs %}
      <tr>
          <td>{{forloop.counter}}</td>
          <td>{{ a.billing_date }}</td>
         {% trans 'Main' as default_branch %}
          <td>{{ a.branch|default_if_none:default_branch }}</td>
          <td><a href="{% url "costs:costs_details" a.pk %}" title="{% trans "Click to see details" %}">
            {{a.name|default_if_none:"&mdash;" }}</a></td>
          <td>{{ a.category }}</td>
          <td>{{a.amount}}</td>
          <td><a href="{% url "costs:costs_update" a.pk %}"">{% trans 'Edit'%}</a> </td>
          <td><a href="{% url "costs:costs_delete" a.pk %}"">{% trans 'Delete'%}</a> </td>
      </tr>
      {% endfor %}
      <tr>
        <th colspan="4">Total</th>
        <td colspan="4"><b>{{total}}</b></td>
      </tr>
    </table>
</div>
{% endblock %}

costs/templates/costs/costs_delete.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <h3>{% trans "Costs:" %} <small>{{costs.category}}</small></h3>

  <div class="row">
    <div class="col-sm-6">
      <form action="{% url "costs:costs_delete" costs.pk  %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-danger" type="submit" value="{% trans "Effacer" %}"</input>
      </form>
      </div>
  </div>

</div>
{% endblock %}

costs/templates/costs/costs_details.html
{% extends "base.html"%}
{% load static %}
{% load i18n %}
{% block content %}

<div class="container">


  <h2>{% trans "Details of the costs" %}</h2>

  <table class="table">
    <tbody>

      <tr>
        <th>{% trans "Creation Date" %}</th><td>{{costs.creation_date}}</td>
        <th>{% trans "Amount" %}</th><td>{{costs.amount}}</td>
        <th>{% trans "Category" %}</th><td>{{costs.category.name}}</td>
        <th>{% trans "Branch" %}</th><td>{{ costs.branch.name|default_if_none:"n.d." }}</td>
      </tr>
      <tr>
        <th>{% trans "Name" %}</th><td>{{costs.name|default_if_none:"n.d."}}</td>
        <th>{% trans "Note" %}</th><td>{{costs.note|default_if_none:"n.d."}}</td>
        {% if costs.article_link %}
        <th>{% trans "Article link" %}</th><td>
        <a href="{{costs.article_link}}">{% trans "Link to article" %}</a></td>
        {% endif %}
      </tr>
      <tr>
        <th>{% trans "Enterprise" %}</th><td>{% if costs.enterprise %}{{costs.enterprise.name}}{% else %}n.d.{% endif %}</td>
        <th>{% trans "Billing Date" %}</th><td>{{costs.billing_date|default_if_none:"n.d."}}</td>
        <th>{% trans "Billing Nr" %}</th><td>{{costs.billing_number|default_if_none:"n.d."}}</td>
      </tr>

    </tbody>
  </table>

</div>



{% endblock %}

{% block footernav %}

{% endblock %}

costs/templates/costs/costs_update.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% crispy form %}
</div>
{% endblock %}
{% block javascript %}
<script type="text/javascript">

$( function() {
     $.datepicker.setDefaults(
       $.datepicker.regional["es"]);
     $( '[id="datetimepicker_es_update"]' ).datepicker({
       dateFormat: "yy-mm-dd"});
}
);
  </script>
{% endblock %}

costs/templates/costs/enterprise_create.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <h2>{% trans 'Adding one Enterprise or Provider'%}</h2>
  {% blocktrans %}
  <p>An enterprise you pay for a service: cleaning, electricity, and so on,  <em>provides</em>
  you a service.</p>
  {% endblocktrans %}
{% crispy form %}
</div>
{% endblock %}

costs/templates/costs/enterprise_delete.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <h3>{% trans "Enterprise:" %} <small>{{enterprise.name}}</small></h3>

  <div class="row">
    <div class="col-sm-6">
      <form action="{% url "costs:enterprise_delete" enterprise.pk  %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-danger" type="submit" value="{% trans "Effacer" %}"</input>
      </form>
      </div>
  </div>

</div>
{% endblock %}

costs/templates/costs/enterprise_details.html
{% extends "base.html"%}
{% load static %}
{% load i18n %}
{% block content %}
<p>
<div class="container">



  <h2>{% trans "Details of the enterprise" %}</h2>

  <table class="table">
    <tbody>

      <tr>
        <th>{% trans "Name" %}</th><td>{{enterprise.name}}</td>
      </tr>

    </tbody>
  </table>

</div>
</p>


{% endblock %}

{% block footernav %}

{% endblock %}

costs/templates/costs/enterprise_update.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% crispy form %}
</div>
{% endblock %}

costs/templates/costs/enterprises.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="container">
    <table class="table table-light">
      <thead class="thead-light">
      <tr>
          <th>{% trans 'Name' %}</th>
          <th>{% trans 'Edit' %}</th>
          <th>{% trans 'Delete' %}</th>
      </tr>
      </thead>

      <tbody>
      {% for a in enterprises %}
      <tr>
          <td>{{ a.name }}</td>
          <td><a href="{% url "costs:enterprise_update" a.pk %}">{% trans 'Edit'%}</a> </td>
          <td><a href="{% url "costs:enterprise_delete" a.pk %}">{% trans 'Delete'%}</a> </td>
      </tr>
      {% endfor %}
    </table>
</div>
{% endblock %}